### ISSUE TITLE
MPII images cropping 

### ISSUE THREAD

**Issue by jessiechouuu** [anewell/pose-hg-demo#4]
Hi,

You mentioned that you adjust the center and scale annotation in MPII dataset.
Would you mind to describe more details of the adjustment in addition to moving down the center?

Thanks!

**Comment by anewell** [comment]
Yep, the code is here: https://github.com/anewell/pose-hg-train/blob/master/src/util/dataset/mpii.lua#L67
It first adjusts the y value down, and then increases the scale.

**Comment by jessiechouuu** [comment]
Thanks for your reply!
