### ISSUE TITLE
about running demo

### ISSUE THREAD

**Issue by JaHangirYin** [anewell/pose-hg-demo#5]
Hi 
When I run _qlua main.lua demo_ it gives some error 
_Unable to connect X11 server (continuing with -nographics)
qlua: cannot open <umich-stacked-hourglass.t7> in mode r  at /home/jiahang/torch/pkg/torch/lib/TH/THDiskFile.c:668
stack traceback:
        [C]: at 0x7fd1a79d79c0
        [C]: at 0x7fd19f92eac0
        [C]: in function 'DiskFile'
        /home/jiahang/torch/install/share/lua/5.1/torch/File.lua:405: in function 'load'
        main.lua:28: in main chunk
Segmentation fault (core dumped)_

I hope I can get your help. Thank you

**Comment by anewell** [comment]
It looks like maybe the model file isn't available in the path, did you download it and put in the right directory?

**Comment by neherh** [comment]
@anewell  is correct, the file 'umich-stacked-hourglass.t7' must in the 'pose-hg-demo' directory (or the directory the main.lua file is in).

**Comment by larklili** [comment]
i have the same problem,have you solved yet?could you please tell me the solution,thanks~

**Comment by neherh** [comment]
Yes. To solve the problem put the .t7 into the same directory as main.lua. @larklili have you tried this?

**Comment by larklili** [comment]
where is .t7?

**Comment by larklili** [comment]
@neherh yeah!i have solved yet.Thanks a lot:)

**Comment by larklili** [comment]
@neherh Do you have run th main.lua predict-[valid or test]?would you please tell me how to solve with .h5 file.I dont know how to get result from it.:)thanks!
