### ISSUE TITLE
Demo results

### ISSUE THREAD

**Issue by dbaranchuk** [anewell/pose-hg-demo#6]
Hi,

I've run your demo code and got pretty weird results:  

| method | Head | Knee | Ankle | Shoulder | Elbow | Wrist | Hip |
| ------- | ------ | ------ | ------ | ------ | ------ | ------ | ------ |
| valid-example | 96.52 | 78.60 | 73.52 | 93.51 | 85.18 | 79.17 | 84.14 |
| valid-ours	   | 96.67	| 83.10 | 79.07 | 94.68 | 88.54 | 83.38 | 87.49 |

I downloaded your pre-trained model and MPII dataset and followed the instructions. Could you explain please why results are much worse than in #1 ? Have you updated this model since that time ?

Thanks!

**Comment by anewell** [comment]
Hm, that's interesting, I did update the model recently, but it is supposed to be a better version. Perhaps I made a mistake, and will look into it.

**Comment by sunke123** [comment]
Hi, the new model can achieve 87.9 on validation.
You just need to select which stage you want.
In this code, the default is stage 2. So, you obtain a worse result.
If you set it as 8, you can get the 87.9.
`local hm = out[stage_num][1]:float()`

**Comment by anewell** [comment]
Thanks for pointing that out, I've updated the file with the fix

**Comment by larklili** [comment]
hi,could you please tell me how to solve with .h5 files?i have get full predictions of MPII
