### ISSUE TITLE
discrepancy between model architecture in  .t7 model and in the demo code

### ISSUE THREAD

**Issue by ShethR** [anewell/pose-hg-demo#9]
Hi, 
I am trying to reproduce the your demo code in tensorflow using the trained .t7 model.
But I guess the model in the demo code( residual.lua & stacked-hourglass-model.lua ) and the model used to trained umich-stacked-hourglass.t7 is different. 

Could you provide the model architecture details used to train umich-stacked-hourglass.t7?

Thank you!

**Comment by anewell** [comment]
Hi, sorry about that, the model file here hasn't been updated in a long time, check out the training code for the most up-to-date version here: https://github.com/anewell/pose-hg-train

**Comment by ShethR** [comment]
ohh I see, 
Thank you!!
